### ISSUE TITLE
[Feat] 당근마켓 상품 상세 페이지 구현

### ISSUE THREAD

**Issue by cchanmi** [THE-SOPT-Joint-Seminar-Danggn/Daangn-iOS#3]
## 🥕  Issue

당근마켓 상품의 상세 페이지를 구현합니다.

## 📝  todo

- [x] 네비게이션 상단바, 버튼 구현 및 홈 화면 이동
- [x] 상품 사진 컬렉션 뷰 구현
- [x] "판매중" 바텀 시트 구현
- [x] 좋아요 버튼 클릭하였을 때 버튼 상태 변화
