### ISSUE TITLE
[FEAT] 상품 상세 페이지 서버 붙이기

### ISSUE THREAD

**Issue by cchanmi** [THE-SOPT-Joint-Seminar-Danggn/Daangn-iOS#9]
## 🥕 Issue

상품 상세 페이지 서버 붙이기

## 📝 todo

- GET
- [ ] 상품 상세 페이지 조회

- PUT
- [x] 상품 좋아요 등록 및 취소
- [x] 상품 판매 상태 변경 요청
